name: Build Test & Deploy
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js "14.x"
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: yarn install --prefer-offline
      - name: Building source
        run: yarn build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
        env:
          CI: true
  deploy:
    name: Deploy to production
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Deploy files
        env:
          SSH_HOST_KEY: ${{secrets.SSH_HOST_KEY}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
          rsync -az --progress -e ssh ./build/ root@parteiduell.de:/var/www/parteiduell.de/production --delete
